name: Test

on:
  push:
    branches:
      - main
      - feature/*

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Data
      - name: Cache data
        uses: actions/cache@v2
        id: cache-data
        with:
          path: data/*
          key: data-v1

      - name: Download data
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install axel -y
          mkdir data
          axel -n 20 http://dl.fbaipublicfiles.com/GENRE/kilt_titles_trie_dict.pkl -o data

      # Models
      - name: Cache models
        uses: actions/cache@v2
        id: cache-models
        with:
          path: models/*
          key: models-v1

      - name: Download models
        if: steps.cache-models.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install axel -y
          mkdir models
          axel -n 20 http://dl.fbaipublicfiles.com/GENRE/fairseq_wikipage_retrieval.tar.gz
          tar -xvf fairseq_wikipage_retrieval.tar.gz --directory models

      # Pip Dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-tests.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip dependencies
        run: pip install -r requirements-test.txt

      # Install Fairseq & Genre
      - name: Install Fairseq
        run: |
          git clone -b fixing_prefix_allowed_tokens_fn --single-branch https://github.com/nicola-decao/fairseq.git
          pip install -e ./fairseq

      - name: Install GENRE
        run: pip install -e .

      # Run tests
      - name: Pytest
        run: pytest tests --verbose